### ISSUE TITLE
Error while building kernal

### ISSUE THREAD

**Issue by ramesh5m** [TF-Hafnium/hafnium#1]
erm2cob@COB-V-0005F:~/Hafnium/hafnium/driver/linux((HEAD detached at 196ed0e))$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KERNEL_PATH=/home/erm2cob/Hafnium/linux/ make
cp -r /home/erm2cob/Hafnium/hafnium/driver/linux/../../vmlib/ /home/erm2cob/Hafnium/hafnium/driver/linux
make -C /home/erm2cob/Hafnium/linux/ HAFNIUM_PATH=/home/erm2cob/Hafnium/hafnium/driver/linux/../.. M=/home/erm2cob/Hafnium/hafnium/driver/linux O= ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules
make[1]: Entering directory '/home/erm2cob/Hafnium/linux'
  CC [M]  /home/erm2cob/Hafnium/hafnium/driver/linux/main.o
In file included from ./include/asm-generic/bug.h:22,
                 from ./arch/arm64/include/asm/bug.h:26,
                 from ./include/linux/bug.h:5,
                 from ./arch/arm64/include/asm/cpufeature.h:23,
                 from ./arch/arm64/include/asm/hwcap.h:9,
                 from ./arch/arm64/include/asm/arch_timer.h:12,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/ktime.h:24,
                 from ./include/linux/hrtimer_defs.h:5,
                 from ./include/linux/hrtimer.h:15,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:18:
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c: In function ‘hf_handle_message’:
./include/linux/kern_levels.h:5:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
    5 | #define KERN_SOH "\001"  /* ASCII Start Of Header */
      |                  ^~~~~~
./include/linux/printk.h:427:11: note: in definition of macro ‘printk_index_wrap’
  427 |   _p_func(_fmt, ##__VA_ARGS__);    \
      |           ^~~~
./include/linux/printk.h:498:2: note: in expansion of macro ‘printk’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~
./include/linux/kern_levels.h:11:18: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR KERN_SOH "3" /* error conditions */
      |                  ^~~~~~~~
./include/linux/printk.h:498:9: note: in expansion of macro ‘KERN_ERR’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:281:3: note: in expansion of macro ‘pr_err’
  281 |   pr_err("Message received without header of length %d\n", len);
      |   ^~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:281:54: note: format string is defined here
  281 |   pr_err("Message received without header of length %d\n", len);
      |                                                     ~^
      |                                                      |
      |                                                      int
      |                                                     %ld
In file included from ./include/asm-generic/bug.h:22,
                 from ./arch/arm64/include/asm/bug.h:26,
                 from ./include/linux/bug.h:5,
                 from ./arch/arm64/include/asm/cpufeature.h:23,
                 from ./arch/arm64/include/asm/hwcap.h:9,
                 from ./arch/arm64/include/asm/arch_timer.h:12,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/ktime.h:24,
                 from ./include/linux/hrtimer_defs.h:5,
                 from ./include/linux/hrtimer.h:15,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:18:
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c: In function ‘hf_vcpu_thread’:
./include/linux/kern_levels.h:5:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
    5 | #define KERN_SOH "\001"  /* ASCII Start Of Header */
      |                  ^~~~~~
./include/linux/printk.h:427:11: note: in definition of macro ‘printk_index_wrap’
  427 |   _p_func(_fmt, ##__VA_ARGS__);    \
      |           ^~~~
./include/linux/printk.h:508:2: note: in expansion of macro ‘printk’
  508 |  printk(KERN_WARNING pr_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~
./include/linux/kern_levels.h:12:22: note: in expansion of macro ‘KERN_SOH’
   12 | #define KERN_WARNING KERN_SOH "4" /* warning conditions */
      |                      ^~~~~~~~
./include/linux/printk.h:508:9: note: in expansion of macro ‘KERN_WARNING’
  508 |  printk(KERN_WARNING pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:420:4: note: in expansion of macro ‘pr_warn’
  420 |    pr_warn("FF-A error %d running VM %d vCPU %d", ret.arg2,
      |    ^~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:420:25: note: format string is defined here
  420 |    pr_warn("FF-A error %d running VM %d vCPU %d", ret.arg2,
      |                        ~^
      |                         |
      |                         int
      |                        %lld
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c: In function ‘hf_sock_recvmsg’:
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:720:43: warning: passing argument 3 of ‘skb_recv_datagram’ makes pointer from integer without a cast [-Wint-conversion]
  720 |  skb = skb_recv_datagram(sk, flags, flags & MSG_DONTWAIT, &err);
In file included from ./include/net/net_namespace.h:43,
                 from ./include/linux/netdevice.h:38,
                 from ./include/net/sock.h:46,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:31:
./include/linux/skbuff.h:3949:17: note: expected ‘int *’ but argument is of type ‘int’
 3949 | struct sk_buff *skb_recv_datagram(struct sock *sk, unsigned int flags, int *err);
      |                 ^~~~~~~~~~~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:720:8: error: too many arguments to function ‘skb_recv_datagram’
  720 |  skb = skb_recv_datagram(sk, flags, flags & MSG_DONTWAIT, &err);
      |        ^~~~~~~~~~~~~~~~~
In file included from ./include/net/net_namespace.h:43,
                 from ./include/linux/netdevice.h:38,
                 from ./include/net/sock.h:46,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:31:
./include/linux/skbuff.h:3949:17: note: declared here
 3949 | struct sk_buff *skb_recv_datagram(struct sock *sk, unsigned int flags, int *err);
      |                 ^~~~~~~~~~~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c: In function ‘hf_sock_create’:
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:765:17: error: ‘sock_no_setsockopt’ undeclared (first use in this function); did you mean ‘sock_setsockopt’?
  765 |   .setsockopt = sock_no_setsockopt,
      |                 ^~~~~~~~~~~~~~~~~~
      |                 sock_setsockopt
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:765:17: note: each undeclared identifier is reported only once for each function it appears in
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:766:17: error: ‘sock_no_getsockopt’ undeclared (first use in this function); did you mean ‘sock_getsockopt’?
  766 |   .getsockopt = sock_no_getsockopt,
      |                 ^~~~~~~~~~~~~~~~~~
      |                 sock_getsockopt
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:770:4: error: ‘const struct proto_ops’ has no member named ‘sendpage’
  770 |   .sendpage = sock_no_sendpage,
      |    ^~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:770:15: error: ‘sock_no_sendpage’ undeclared (first use in this function); did you mean ‘sock_no_sendmsg’?
  770 |   .sendpage = sock_no_sendpage,
      |               ^~~~~~~~~~~~~~~~
      |               sock_no_sendmsg
In file included from ./include/asm-generic/bug.h:22,
                 from ./arch/arm64/include/asm/bug.h:26,
                 from ./include/linux/bug.h:5,
                 from ./arch/arm64/include/asm/cpufeature.h:23,
                 from ./arch/arm64/include/asm/hwcap.h:9,
                 from ./arch/arm64/include/asm/arch_timer.h:12,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/ktime.h:24,
                 from ./include/linux/hrtimer_defs.h:5,
                 from ./include/linux/hrtimer.h:15,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:18:
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c: In function ‘hf_init’:
./include/linux/kern_levels.h:5:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
    5 | #define KERN_SOH "\001"  /* ASCII Start Of Header */
      |                  ^~~~~~
./include/linux/printk.h:427:11: note: in definition of macro ‘printk_index_wrap’
  427 |   _p_func(_fmt, ##__VA_ARGS__);    \
      |           ^~~~
./include/linux/printk.h:498:2: note: in expansion of macro ‘printk’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~
./include/linux/kern_levels.h:11:18: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR KERN_SOH "3" /* error conditions */
      |                  ^~~~~~~~
./include/linux/printk.h:498:9: note: in expansion of macro ‘KERN_ERR’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:990:4: note: in expansion of macro ‘pr_err’
  990 |    pr_err("FF-A error code %d\n", ffa_ret.arg2);
      |    ^~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:990:29: note: format string is defined here
  990 |    pr_err("FF-A error code %d\n", ffa_ret.arg2);
      |                            ~^
      |                             |
      |                             int
      |                            %lld
In file included from ./include/asm-generic/bug.h:22,
                 from ./arch/arm64/include/asm/bug.h:26,
                 from ./include/linux/bug.h:5,
                 from ./arch/arm64/include/asm/cpufeature.h:23,
                 from ./arch/arm64/include/asm/hwcap.h:9,
                 from ./arch/arm64/include/asm/arch_timer.h:12,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/ktime.h:24,
                 from ./include/linux/hrtimer_defs.h:5,
                 from ./include/linux/hrtimer.h:15,
                 from /home/erm2cob/Hafnium/hafnium/driver/linux/main.c:18:
./include/linux/kern_levels.h:5:18: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
    5 | #define KERN_SOH "\001"  /* ASCII Start Of Header */
      |                  ^~~~~~
./include/linux/printk.h:427:11: note: in definition of macro ‘printk_index_wrap’
  427 |   _p_func(_fmt, ##__VA_ARGS__);    \
      |           ^~~~
./include/linux/printk.h:498:2: note: in expansion of macro ‘printk’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~
./include/linux/kern_levels.h:11:18: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR KERN_SOH "3" /* error conditions */
      |                  ^~~~~~~~
./include/linux/printk.h:498:9: note: in expansion of macro ‘KERN_ERR’
  498 |  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:992:4: note: in expansion of macro ‘pr_err’
  992 |    pr_err("Unexpected FF-A function %#x\n", ffa_ret.func);
      |    ^~~~~~
/home/erm2cob/Hafnium/hafnium/driver/linux/main.c:992:39: note: format string is defined here
  992 |    pr_err("Unexpected FF-A function %#x\n", ffa_ret.func);
      |                                     ~~^
      |                                       |
      |                                       unsigned int
      |                                     %#llx
make[3]: *** [scripts/Makefile.build:243: /home/erm2cob/Hafnium/hafnium/driver/linux/main.o] Error 1
make[2]: *** [/home/erm2cob/Hafnium/linux/Makefile:1913: /home/erm2cob/Hafnium/hafnium/driver/linux] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/home/erm2cob/Hafnium/linux'
make: *** [Makefile:36: all] Error 2

**Comment by odeprez** [comment]
Hi Ramesh,
Thanks for reporting through the github issue tracker. We're just in the process of migrating to using this tool so apologies for leaving this query unattended.
Is this still actually an issue at your end? Can you tell a bit more about what you're trying to achieve?
Just as a reminder prerequisites and build instructions are in those pages just in case you missed them:
https://hafnium.readthedocs.io/en/latest/getting_started/prerequisites.html

**Comment by odeprez** [comment]
Closing this issue as no answer since end Jan.
