### ISSUE TITLE
Errors occurred during compilation using clang version 17.0.6 to compiles.

### ISSUE THREAD

**Issue by mingxien** [TF-Hafnium/hafnium#3]
There are two compilation error when using clang 17.0.6.
The toolchain package of llvm comes from [llvmorg-17.0.6](https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.6).

1. clang: error: mismatch between architecture and environment in target triple 'aarch64-none-eabi'; did you mean 'aarch64-none-elf'? [-Werror,-Winvalid-command-line-argument]
2. In file included from hafnium/test/inc/test/hftest.h:192:
hafnium/test/inc/test/hftest_impl.h:150:2: error: type name does not allow function specifier to be specified
  150 |         noreturn void (*abort)(void);
      |         ^
clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/lib/clang/17/include/stdnoreturn.h:13:18: note: expanded from macro 'noreturn'
   13 | #define noreturn _Noreturn

Could you assist with fixing these compilation error, and do hafnium have any toolchain upgrade plan?

**Comment by odeprez** [comment]
Hi mingxien,
This message to acknowledge your query.
Note the recommended toolchain in the hafnium pre-requisites documentation pages is LLVM/clang 15.0.6:
https://hafnium.readthedocs.io/en/latest/getting_started/prerequisites.html#toolchain

However, we agree that having the capability for building with the latest toolchain is valuable.
We have couple of changes internally that we would be able to share shortly. We'll keep you posted.

**Comment by mingxien** [comment]
Hi @odeprez,

Thanks for your response and help. I've taken note of the recommended toolchain version, which is 15.0.6. However, I'm aware that newer toolchain versions can address CVEs, that's why I'm attempting to compile hafinum with LLVM/clang 17.0.6.

**Comment by J-Alves** [comment]
Hi,
We have merged patches to enable support of the clang-18 build:
https://review.trustedfirmware.org/c/hafnium/hafnium/+/29666/10
https://review.trustedfirmware.org/c/hafnium/hafnium/+/29667/19
https://review.trustedfirmware.org/c/hafnium/hafnium/+/29668/22
Please try at your end and let me know if this works for you so we can close the issue.
Best regards,
Joao
