### ISSUE TITLE
Does Hafnium currently support specifying partition ID?

### ISSUE THREAD

**Issue by mingxien** [TF-Hafnium/hafnium#4]
From the source code perspective, the ID is assigned during `vm_init()` as `vm_count + HF_VM_ID_OFFSET`.
https://github.com/TF-Hafnium/hafnium/blob/main/src/vm.c#L118
In actual experiments, when specifying an ID in test SP manifest, the assigned ID number still comes from `vm_count + HF_VM_ID_OFFSET`.

FF-A specification mentions partition identification can be specified in manifest of partition or allocated and assigned by the partition manager.
Did we missing something? Or is it just that Hafnium doesn't support specifying IDs yet? If so, will it support them in the future?

**Comment by odeprez** [comment]
Hi mingxien,

That's correct, Hafnium ignores the id field in secure partition manifests.
As you mentioned, it is an implementation defined choice to  the partition manager to choose the id assignment policy. 
Hafnium chose its policy to assign partition IDs while booting (hence ignores the id field).

**Comment by mingxien** [comment]
Got it! So I assume Hafnium won't support specifying ID in the future.
If we propose an implementation for specifying ID through the pull request, would you consider accepting it?

**Comment by odeprez** [comment]
Hi this is an open source project, so you can propose whatever is sensible to you as long as it follows the FF-A standard.
For starters I would suggest aligning with the EL3 SPMC implementation which actually supports the partition manifest id field, and in general we prefer aligning the different FF-A implementations to common designs.
OP-TEE FF-A SPMC might also implement it so worth a look at how it's done and align as well.

**Comment by mingxien** [comment]
Hi @odeprez ,

Thanks for your suggestions. We will reference the open projects you mentioned in our implementation, and we'll share the results with you once it's completed.
