### ISSUE TITLE
An ASSERT ERROR occurs after SP1 finishes handling the interrupts when SP2 is initailized. 

### ISSUE THREAD

**Issue by mingxien** [TF-Hafnium/hafnium#6]
The scenario occurs when SP1 enables interrupt during the initialisation process, and an interrupt is tiggered just as SP2 is initailizing. The Hafnium switches execution right to SP1 to handle the interrupt, and after SP1 finishes handling the interrupt and call `FFA_MSG_WAIT` invocation, the following error occurs.
> Panic: ASSERT: hafnium/src/arch/aarch64/plat/ffa/spmc.c:2068:current->rt_model == RTM_SP_INIT

A step-by-step example is as follows:
1. SP1 registers the interrupt handler and enables pIRQ ID 986 with HF_INTERRUPT_ENABLE invocation during the initialisation process.
2. The pIRQ ID 986 is triggered while SP2 is initailising.
3. Hafnium forwards the interrupt to SP1.
4. SP1 enters the interrupt handler and deactivate pIRQ with HF_INTERRUPT_DEACTIVATE invocation.
5. After SP1 finishes handling the interrupt, it uses FFA_MSG_WAIT invocation to return to Hafnium.
6. ASSERT occurs.

This seems to be because SP1 enters the `VCPU_STATE_WAITING` state after initialisation, causing the RTM to be set to `RTM_SEC_INTERRUPT` during interrupt handling process. https://github.com/TF-Hafnium/hafnium/blob/6acc53703857e1b699fa6c28840a6af542f9c47f/src/arch/aarch64/plat/ffa/spmc.c#L1540
However, Hafnium runs into ASSERT error when SP1 uses FFA_MSG_WAIT invocation because the initialisation has not yet completed.(with spmc_booted not being raised) https://github.com/TF-Hafnium/hafnium/blob/6acc53703857e1b699fa6c28840a6af542f9c47f/src/arch/aarch64/plat/ffa/spmc.c#L2068

**Comment by J-Alves** [comment]
Hi,
Trying to recreate this case.
Thanks for reporting.

**Comment by J-Alves** [comment]
Hi,
I noticed a remark that this sequence needed to be addressed when working on a similar issue you asked for.
I want to absorb such functionality as part of a more encompassing refactoring work that is currently in progress.
Meanwhile, the fix given the current state of the code: https://review.trustedfirmware.org/c/hafnium/hafnium/+/31115
Give that a try, and let me know if it works for you.
Cheers

**Comment by mingxien** [comment]
Hi @J-Alves,
 It works, thanks for your patch.

**Comment by J-Alves** [comment]
Hi @mingxien we merged a patch that shall fix this issue.
https://review.trustedfirmware.org/c/hafnium/hafnium/+/26519/28
Closing this issue. Please feel free to message us again, if you have further queries/concerns.
Cheers

**Comment by J-Alves** [comment]
Closed as per previous comment.
